// Mocks generated by Mockito 5.4.2 from annotations
// in app/test/infra/gateways/user/auth_user_gateway_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:app/data/repositories/user_repository.dart' as _i2;
import 'package:app/domain/entities/user.dart' as _i3;
import 'package:app/infra/gateways/user/auth_user_gateway.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthUserRepository_0 extends _i1.SmartFake
    implements _i2.AuthUserRepository {
  _FakeAuthUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthUserGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUserGateway extends _i1.Mock implements _i4.AuthUserGateway {
  @override
  _i2.AuthUserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeAuthUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthUserRepository);
  @override
  set repository(_i2.AuthUserRepository? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.User> auth(dynamic dto) => (super.noSuchMethod(
        Invocation.method(
          #auth,
          [dto],
        ),
        returnValue: _i5.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #auth,
            [dto],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #auth,
            [dto],
          ),
        )),
      ) as _i5.Future<_i3.User>);
}
